### ISSUE TITLE
[FEATURE] User 엔티티에 프로필 사진(profilePic) 필드 추가 🖼️

### ISSUE THREAD

**Issue by Haejeong079** [IronBirdProject/IronBird_Server#10]
## 📋 Description
User 엔티티에서 소셜 로그인 사용자와 자체 회원의 프로필 사진 관리가 필요. 
- 소셜 로그인 사용자는 소셜 제공자로부터 프로필 사진 URL을 가져옴.
- 자체 회원 가입자는 기본 프로필 사진 URL이 설정됩니다.(디폴트)

---

## ✅ Tasks
- [ ] `User` 엔티티에 `profilePic` 필드 추가 (String 타입)
- [ ] 자체 회원 가입 시 기본 프로필 사진 설정 로직 추가
- [ ] 소셜 로그인 시 소셜 제공자로부터 프로필 사진 설정 로직 추가

---

## 🚀 Goal
- 소셜 로그인과 자체 회원 가입 시 프로필 사진을 각각 적절히 설정할 수 있도록 User 엔티티를 확장.
